### ISSUE TITLE
UpsertInterface and UpsertTrait are missed

### ISSUE THREAD

**Issue by volha-pivavarchyk** [acquia/mc-cs-plugin-custom-objects#288]
### Mautic Version

4.2.x series

### PHP version

8.0.24

### What browsers are you seeing the problem on?

Chrome

### What happened?

A bug happened!

The 500 er is appered when use the current version of the CustomObject with Mautic v4.4.4 or on 5.x branch

### How can we reproduce this issue?

Step 1: Install a new Mautic instance (v4.4.4 or 5.x)
Step 2. Install the CustomBundle
Step 3. Run composer install
Step 4. Try to run migrations
Step 5. The error appears
![image](https://user-images.githubusercontent.com/96085911/199002492-42b19465-7d87-4d31-9c7a-dd12f9cac2be.png)

Step 6. Try to open in the browser
Step 7. 500er is here

### Relevant log output

```shell
PHP Fatal error:  Uncaught Error: Interface 'Mautic\CoreBundle\Entity\UpsertInterface' not found in /var/www/html/plugins/CustomObjectsBundle/Entity/CustomItem.php:45
Stack trace:
#0 /var/www/html/vendor/composer/ClassLoader.php(571): include()
#1 /var/www/html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/html/v...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('MauticPlugin\\Cu...')
#3 [internal function]: spl_autoload_call('MauticPlugin\\Cu...')
#4 /var/www/html/app/bundles/CoreBundle/DependencyInjection/Builder/Metadata/EntityMetadata.php(55): ReflectionClass->__construct('\\MauticPlugin\\C...')
#5 /var/www/html/app/bundles/CoreBundle/DependencyInjection/Builder/BundleMetadataBuilder.php(164): Mautic\CoreBundle\DependencyInjection\Builder\Metadata\EntityMetadata->build()
#6 /var/www/html/app/bundles/CoreBundle/DependencyInjection/Builder/BundleMetadataBuilder.php(158): Mautic\CoreBundle\DependencyInjection\Builder\BundleMetadataBuilder->buildMappings(Object(Mautic\CoreBun in /var/www/html/plugins/CustomObjectsBundle/Entity/CustomItem.php on line 45

Fatal error: Uncaught Error: Interface 'Mautic\CoreBundle\Entity\UpsertInterface' not found in /var/www/html/plugins/CustomObjectsBundle/Entity/CustomItem.php:45
Stack trace:
#0 /var/www/html/vendor/composer/ClassLoader.php(571): include()
#1 /var/www/html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/html/v...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('MauticPlugin\\Cu...')
#3 [internal function]: spl_autoload_call('MauticPlugin\\Cu...')
#4 /var/www/html/app/bundles/CoreBundle/DependencyInjection/Builder/Metadata/EntityMetadata.php(55): ReflectionClass->__construct('\\MauticPlugin\\C...')
#5 /var/www/html/app/bundles/CoreBundle/DependencyInjection/Builder/BundleMetadataBuilder.php(164): Mautic\CoreBundle\DependencyInjection\Builder\Metadata\EntityMetadata->build()
#6 /var/www/html/app/bundles/CoreBundle/DependencyInjection/Builder/BundleMetadataBuilder.php(158): Mautic\CoreBundle\DependencyInjection\Builder\BundleMetadataBuilder->buildMappings(Object(Mautic\CoreBun in /var/www/html/plugins/CustomObjectsBundle/Entity/CustomItem.php on line 45
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
The upsert interface issue will be fixed with https://github.com/mautic/mautic/pull/11654. Please review it if you want to speed up the merge.

Until then you'll have to use some older version of this plugin.

**Comment by volha-pivavarchyk** [comment]
The [PR #11654](https://github.com/mautic/mautic/pull/11654) fixes this issue. Thanks!
